<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Niladri Prasad Padhy</Authors>
    <Company>Nuventra</Company>
    <Copyright>Copyright © 2026 Niladri Prasad Padhy</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/nuvyntralabs/NuvexaMQ</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nuvyntralabs/NuvexaMQ</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <Version>0.1.1</Version>
    <PackageVersion>0.1.1</PackageVersion>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <NeutralLanguage>en</NeutralLanguage>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
