#!/bin/bash
set -e
mkdir -p "/Library/Application Support/NuvexaMQ/data" "/Library/Logs/NuvexaMQ"
chmod 755 "/Applications/NuvexaMQ.app/Contents/MacOS/Nuventra.NuvexaMQ.Desktop" \
  "/Applications/NuvexaMQ.app/Contents/Resources/server/nuvexamq" \
  "/Applications/NuvexaMQ.app/Contents/Resources/server/nuvexamq-desktop"
launchctl bootout system/com.nuventra.nuvexamq >/dev/null 2>&1 || true
launchctl bootstrap system /Library/LaunchDaemons/com.nuventra.nuvexamq.plist
exit 0
